apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  ports:
    - port: 80
      targetPort: 80
    - name: http
      port: 443
      targetPort: http
      nodePort: 30080
  selector:
    app: webui
  type: NodePort
