apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: DOCKER_USER/DOCKER_APP:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80
