apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: DOCKER_USER/DOCKER_APP:BUILD_NUMBER
        ports:
          - name: http-port
            containerPort: 80
